# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /app
COPY . /app

# Copy the requirements.txt file into the container
# COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application into the container

# Command to run the application
CMD ["python", "Q1.py"]


#cmd to build the  docker image-  docker build -t cpu-monitor
#cmd to run the docker file -